### ISSUE TITLE
error when installing under ubuntu 13.10

### ISSUE THREAD

**Issue by shamaho** [clemtibs/wikidpad-utils#1]
The install log runs as follows:

sam@sam-Latitude-D620:~/Downloads/wikipad-utils/wikidpad-utils-master$ sudo python setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating wikidpad_utils_master.egg-info
writing wikidpad_utils_master.egg-info/PKG-INFO
writing top-level names to wikidpad_utils_master.egg-info/top_level.txt
writing dependency_links to wikidpad_utils_master.egg-info/dependency_links.txt
writing manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
reading manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
writing manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
warning: install_lib: 'build/lib.linux-i686-2.7' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-i686
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/EGG-INFO
installing scripts to build/bdist.linux-i686/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
error: file '/home/sam/Downloads/wikipad-utils/wikidpad-utils-master/bin/wikidpad' does not exist
sam@sam-Latitude-D620:~/Downloads/wikipad-utils/wikidpad-utils-master$ 

Context Info:

Wikipad installed into /opt/Wikipad   (first W in uppercase)
setup files unzipped to : ~/Downloads/wikipad-utils/wikidpad-utils-master

sudo python setup.py install  - ran from the location of the unzip

**Comment by clemtibs** [comment]
Wow, I accidentally ignored the folder that the script was in. I've included it and updated the instructions. Give that a try and let me know how it works.

**Comment by shamaho** [comment]
I think there is still some problem, probably assuming Python is version 2.7 maybe, when in fact in my system is 2.8, log follows:

sam@sam-Latitude-D620:~/Downloads/wikidpad-utils-master$ sudo python setup.py install
[sudo] password for sam: 
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating wikidpad_utils_master.egg-info
writing wikidpad_utils_master.egg-info/PKG-INFO
writing top-level names to wikidpad_utils_master.egg-info/top_level.txt
writing dependency_links to wikidpad_utils_master.egg-info/dependency_links.txt
writing manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
reading manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
writing manifest file 'wikidpad_utils_master.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
warning: install_lib: 'build/lib.linux-i686-2.7' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-i686
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/EGG-INFO
installing scripts to build/bdist.linux-i686/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting scripts/wikidpad -> build/scripts-2.7
changing mode of build/scripts-2.7/wikidpad from 644 to 755
creating build/bdist.linux-i686/egg/EGG-INFO/scripts
copying build/scripts-2.7/wikidpad -> build/bdist.linux-i686/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-i686/egg/EGG-INFO/scripts/wikidpad to 755
copying wikidpad_utils_master.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying wikidpad_utils_master.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying wikidpad_utils_master.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying wikidpad_utils_master.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/wikidpad_utils_master-0.0.1-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing wikidpad_utils_master-0.0.1-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/wikidpad_utils_master-0.0.1-py2.7.egg
Extracting wikidpad_utils_master-0.0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding wikidpad-utils-master 0.0.1 to easy-install.pth file
Installing wikidpad script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wikidpad_utils_master-0.0.1-py2.7.egg
Processing dependencies for wikidpad-utils-master==0.0.1
Finished processing dependencies for wikidpad-utils-master==0.0.1
sam@sam-Latitude-D620:~/Downloads/wikidpad-utils-master$ wikipad
wikipad: command not found
sam@sam-Latitude-D620:~/Downloads/wikidpad-utils-master$

**Comment by shamaho** [comment]
Sorry, wrong info before. It seems to be working just fine - at least when invoking wikidpad from command line.

I had wikipad installed under /opt/WikiPad instead of /WikidPad, a simple rename made it all work !

thank you very much for ultra-fast response !

**Comment by clemtibs** [comment]
Yes, what you stumbled on was the weird naming of the program. Wiki-D-Pad.
I made the same mistakes myself at one point with that. Let me know if you
have any other issues.
